//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 12:23:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "", elementFormDefault = XmlNsForm.QUALIFIED) package no.uis.bigdata.hadoop.model.jaxb;

import javax.xml.bind.annotation.XmlNsForm;