//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 12:23:32 PM CEST 
//


package no.uis.bigdata.hadoop.common.model.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the no.uis.avro.generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Page_QNAME = new QName("", "page");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.uis.avro.generated
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Page }
     */
    public Page createPageType() {
        return new Page();
    }

    /**
     * Create an instance of {@link NamespacesType }
     */
    public NamespacesType createNamespacesType() {
        return new NamespacesType();
    }

    /**
     * Create an instance of {@link ContributorType }
     */
    public ContributorType createContributorType() {
        return new ContributorType();
    }

    /**
     * Create an instance of {@link TextType }
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link RevisionType }
     */
    public RevisionType createRevisionType() {
        return new RevisionType();
    }

    /**
     * Create an instance of {@link LogParamsType }
     */
    public LogParamsType createLogParamsType() {
        return new LogParamsType();
    }

    /**
     * Create an instance of {@link RedirectType }
     */
    public RedirectType createRedirectType() {
        return new RedirectType();
    }

    /**
     * Create an instance of {@link CommentType }
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link UploadType }
     */
    public UploadType createUploadType() {
        return new UploadType();
    }

    /**
     * Create an instance of {@link NamespaceType }
     */
    public NamespaceType createNamespaceType() {
        return new NamespaceType();
    }

    /**
     * Create an instance of {@link LogTextType }
     */
    public LogTextType createLogTextType() {
        return new LogTextType();
    }

    /**
     * Create an instance of {@link DiscussionThreadingInfo }
     */
    public DiscussionThreadingInfo createDiscussionThreadingInfo() {
        return new DiscussionThreadingInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Page }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "page")
    public JAXBElement<Page> createPage(Page value) {
        return new JAXBElement<Page>(_Page_QNAME, Page.class, null, value);
    }

}
