//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 12:23:32 PM CEST 
//


package no.uis.bigdata.hadoop.common.model.jaxb;

import no.uis.bigdata.hadoop.xml.xmlreader.XMLConvertible;
import no.uis.bigdata.hadoop.common.model.jaxb.parser.XMLPageMarshaller;
import no.uis.bigdata.hadoop.common.model.jaxb.parser.XMLPageUnMarshaller;

import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Page complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="Page">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ns" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="redirect" type="{http://www.mediawiki.org/xml/export-pages/}RedirectType" minOccurs="0"/>
 *         &lt;element name="restrictions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="revision" type="{http://www.mediawiki.org/xml/export-pages/}RevisionType"/>
 *           &lt;element name="upload" type="{http://www.mediawiki.org/xml/export-pages/}UploadType"/>
 *         &lt;/choice>
 *         &lt;element name="discussionthreadinginfo" type="{http://www.mediawiki.org/xml/export-pages/}DiscussionThreadingInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Page", propOrder = {
        "title",
        "ns",
        "id",
        "redirect",
        "restrictions",
        "revisionOrUpload",
        "discussionthreadinginfo"
})
public class Page implements XMLConvertible<Page> {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger ns;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    protected RedirectType redirect;
    protected String restrictions;
    @XmlElements({
            @XmlElement(name = "revision", type = RevisionType.class),
            @XmlElement(name = "upload", type = UploadType.class)
    })
    protected List<Object> revisionOrUpload;
    protected DiscussionThreadingInfo discussionthreadinginfo;


    @Override
    public String marshall(Page page) throws JAXBException {
        return XMLPageMarshaller.marshallToString(page);
    }

    @Override
    public Page unMarshall(String str) throws JAXBException {
        return XMLPageUnMarshaller.unMarshallFromString(str);
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the ns property.
     *
     * @return possible object is
     *         {@link BigInteger }
     */
    public BigInteger getNs() {
        return ns;
    }

    /**
     * Sets the value of the ns property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setNs(BigInteger value) {
        this.ns = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link BigInteger }
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the redirect property.
     *
     * @return possible object is
     *         {@link RedirectType }
     */
    public RedirectType getRedirect() {
        return redirect;
    }

    /**
     * Sets the value of the redirect property.
     *
     * @param value allowed object is
     *              {@link RedirectType }
     */
    public void setRedirect(RedirectType value) {
        this.redirect = value;
    }

    /**
     * Gets the value of the restrictions property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRestrictions() {
        return restrictions;
    }

    /**
     * Sets the value of the restrictions property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRestrictions(String value) {
        this.restrictions = value;
    }

    /**
     * Gets the value of the revisionOrUpload property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the revisionOrUpload property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRevisionOrUpload().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link RevisionType }
     * {@link UploadType }
     */
    public List<Object> getRevisionOrUpload() {
        if (revisionOrUpload == null) {
            revisionOrUpload = new ArrayList<Object>();
        }
        return this.revisionOrUpload;
    }

    /**
     * Gets the value of the discussionthreadinginfo property.
     *
     * @return possible object is
     *         {@link DiscussionThreadingInfo }
     */
    public DiscussionThreadingInfo getDiscussionthreadinginfo() {
        return discussionthreadinginfo;
    }

    /**
     * Sets the value of the discussionthreadinginfo property.
     *
     * @param value allowed object is
     *              {@link DiscussionThreadingInfo }
     */
    public void setDiscussionthreadinginfo(DiscussionThreadingInfo value) {
        this.discussionthreadinginfo = value;
    }

}
