/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.uis.bigdata.hadoop.common.model.avro;

import org.apache.avro.Schema;

import javax.xml.datatype.XMLGregorianCalendar;

@SuppressWarnings("all")
/** A date stored as a timestamp, in ms UTC. */
public class _Date extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new Schema.Parser().parse("{\"type\":\"record\",\"name\":\"_Date\",\"namespace\":\"no.uis.bigdata.hadoop.common.model.avro\",\"doc\":\"A date stored as a timestamp, in ms UTC.\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\",\"default\":\"0\"}]}");
    public long timestamp;

    public _Date(XMLGregorianCalendar timestamp) {
        this.timestamp=timestamp.getMillisecond();
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    public _Date() {
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return timestamp;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                timestamp = (java.lang.Long) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
}
