/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.uis.bigdata.hadoop.common.model.avro;

@SuppressWarnings("all")
public enum CaseType {
    FIRST_LETTER, CASE_SENSITIVE, CASE_INSENSITIVE, UNSET;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CaseType\",\"namespace\":\"no.uis.bigdata.hadoop.common.model.avro\",\"symbols\":[\"FIRST_LETTER\",\"CASE_SENSITIVE\",\"CASE_INSENSITIVE\",\"UNSET\"]}");
}
