/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.uis.bigdata.hadoop.common.model.avro;

@SuppressWarnings("all")
public class TextType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextType\",\"namespace\":\"no.uis.bigdata.hadoop.common.model.avro\",\"fields\":[{\"name\":\"value\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"space\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"deleted\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"DeletedFlagType\",\"symbols\":[\"DELETED\",\"UNSET\"]}],\"default\":\"null\"},{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"bytes\",\"type\":[\"null\",\"string\"],\"default\":\"null\"}]}");
    public java.lang.CharSequence value;
    public java.lang.CharSequence space;
    public no.uis.bigdata.hadoop.common.model.avro.DeletedFlagType deleted;
    public java.lang.CharSequence id;
    public java.lang.CharSequence bytes;

    public TextType(no.uis.bigdata.hadoop.common.model.jaxb.TextType text) {
        this.value = text.getValue();
        this.space = text.getSpace();
        this.deleted =  text.getDeleted()==null?DeletedFlagType.UNSET:DeletedFlagType.DELETED;
        this.id = text.getId();
        this.bytes = text.getBytes()==null?null:text.getBytes().toString();
    }

    public TextType() {
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return value;
            case 1:
                return space;
            case 2:
                return deleted;
            case 3:
                return id;
            case 4:
                return bytes;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                value = (java.lang.CharSequence) value$;
                break;
            case 1:
                space = (java.lang.CharSequence) value$;
                break;
            case 2:
                deleted = (no.uis.bigdata.hadoop.common.model.avro.DeletedFlagType) value$;
                break;
            case 3:
                id = (java.lang.CharSequence) value$;
                break;
            case 4:
                bytes = (java.lang.CharSequence) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
}
