/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.uis.bigdata.hadoop.common.model.avro;

@SuppressWarnings("all")
public class UploadType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UploadType\",\"namespace\":\"no.uis.bigdata.hadoop.common.model.avro\",\"fields\":[{\"name\":\"timestamp\",\"type\":{\"type\":\"record\",\"name\":\"_Date\",\"doc\":\"A date stored as a timestamp, in ms UTC.\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\",\"default\":\"0\"}]}},{\"name\":\"contributor\",\"type\":{\"type\":\"record\",\"name\":\"ContributorType\",\"fields\":[{\"name\":\"username\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"ip\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"deleted\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"DeletedFlagType\",\"symbols\":[\"DELETED\",\"UNSET\"]}],\"default\":\"null\"}]}},{\"name\":\"comment\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"filename\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"src\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"size\",\"type\":\"string\",\"default\":\"\"}]}");
    public no.uis.bigdata.hadoop.common.model.avro._Date timestamp;
    public no.uis.bigdata.hadoop.common.model.avro.ContributorType contributor;
    public java.lang.CharSequence comment;
    public java.lang.CharSequence filename;
    public java.lang.CharSequence src;
    public java.lang.CharSequence size;

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    public UploadType() {
    }

    public UploadType(no.uis.bigdata.hadoop.common.model.jaxb.UploadType uploadType) {
        this.timestamp = new _Date(uploadType.getTimestamp());
        this.contributor = new ContributorType(uploadType.getContributor());
        this.comment = uploadType.getComment();
        this.filename = uploadType.getFilename();
        this.src = uploadType.getSrc();
        this.size = uploadType.getSize().toString();
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return timestamp;
            case 1:
                return contributor;
            case 2:
                return comment;
            case 3:
                return filename;
            case 4:
                return src;
            case 5:
                return size;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                timestamp = (no.uis.bigdata.hadoop.common.model.avro._Date) value$;
                break;
            case 1:
                contributor = (no.uis.bigdata.hadoop.common.model.avro.ContributorType) value$;
                break;
            case 2:
                comment = (java.lang.CharSequence) value$;
                break;
            case 3:
                filename = (java.lang.CharSequence) value$;
                break;
            case 4:
                src = (java.lang.CharSequence) value$;
                break;
            case 5:
                size = (java.lang.CharSequence) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
}
