/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.uis.bigdata.hadoop.model.avro;

@SuppressWarnings("all")
public enum DeletedFlagType {
    DELETED, UNSET;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DeletedFlagType\",\"namespace\":\"no.uis.bigdata.hadoop.model.avro\",\"symbols\":[\"DELETED\",\"UNSET\"]}");
}
