/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.uis.bigdata.hadoop.model.avro;

@SuppressWarnings("all")
public class LogTextType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogTextType\",\"namespace\":\"no.uis.bigdata.hadoop.model.avro\",\"fields\":[{\"name\":\"value\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"deleted\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"DeletedFlagType\",\"symbols\":[\"DELETED\",\"UNSET\"]}],\"default\":\"null\"}]}");
    public java.lang.CharSequence value;
    public no.uis.bigdata.hadoop.model.avro.DeletedFlagType deleted;

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return value;
            case 1:
                return deleted;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                value = (java.lang.CharSequence) value$;
                break;
            case 1:
                deleted = (no.uis.bigdata.hadoop.model.avro.DeletedFlagType) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
}
