/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.uis.bigdata.hadoop.model.avro;

@SuppressWarnings("all")
public class NamespacesType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NamespacesType\",\"namespace\":\"no.uis.bigdata.hadoop.model.avro\",\"fields\":[{\"name\":\"namespace\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"NamespaceType\",\"fields\":[{\"name\":\"value\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"key\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"_case\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"CaseType\",\"symbols\":[\"FIRST_LETTER\",\"CASE_SENSITIVE\",\"CASE_INSENSITIVE\",\"UNSET\"]}],\"default\":\"null\"}]}}],\"default\":\"null\"}]}");
    public java.util.List<no.uis.bigdata.hadoop.model.avro.NamespaceType> namespace;

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return namespace;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                namespace = (java.util.List<no.uis.bigdata.hadoop.model.avro.NamespaceType>) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
}
