/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.uis.bigdata.hadoop.model.avro;

@SuppressWarnings("all")
public class NamespaceType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NamespaceType\",\"namespace\":\"no.uis.bigdata.hadoop.model.avro\",\"fields\":[{\"name\":\"value\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"key\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"_case\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"CaseType\",\"symbols\":[\"FIRST_LETTER\",\"CASE_SENSITIVE\",\"CASE_INSENSITIVE\",\"UNSET\"]}],\"default\":\"null\"}]}");
    public java.lang.CharSequence value;
    public java.lang.CharSequence key;
    public no.uis.bigdata.hadoop.model.avro.CaseType _case;

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return value;
            case 1:
                return key;
            case 2:
                return _case;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                value = (java.lang.CharSequence) value$;
                break;
            case 1:
                key = (java.lang.CharSequence) value$;
                break;
            case 2:
                _case = (no.uis.bigdata.hadoop.model.avro.CaseType) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
}
